services:
  migrations:
    image: ${DOCKER_HUB}/jackc/tern:latest
    entrypoint: [ "/tern", "migrate", "--migrations", "/app/migrations", "--conn-string",
                  "postgresql://postgres:${POSTGRES_PASSWORD:-pass}@postgres:5432/${POSTGRES_DB:-uni}?sslmode=disable", "--version-table", "uni_schema_version" ]
    volumes:
      - ./migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: ${DOCKER_HUB}/postgres:15
    restart: unless-stopped
    command: [ "postgres", "-c", "max_connections=500" ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-uni}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
